/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import DAO.DetalleEntradaDAO;
import DAO.EntradaDAO;
import Modelo.DetalleEntrada;
import Modelo.Entrada;
import DAO.SalidaDAO;
import DAO.DetalleSalidaDAO;
import DAO.ProductoDAO;
import Modelo.DetalleSalida;
import Modelo.Iva;
import Modelo.Producto;
import Modelo.Salida;
import Modelo.Usuario;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

public class formDetalleSalidaEdit extends javax.swing.JFrame {

    Usuario sysUser;
    String identra;
    public formDetalleSalidaEdit() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public formDetalleSalidaEdit(String id, Usuario user) {
        initComponents();
        this.sysUser = user;
        this.identra = id;
        this.setLocationRelativeTo(null);
        this.getPorcentaje();
        this.getDatosProducto();  
        this.getproduct();
        this.getsalida();
    }
    

    public void getDatosProducto(){
        
        Salida entra = new Salida();
        SalidaDAO entraDAO = new SalidaDAO();
        
        System.out.println(identra);
        entra = entraDAO.leer(Integer.parseInt(identra));

        txtSubTotal.setText(String.valueOf(entra.getSubtotal()));
        txtTotal.setText(String.valueOf(entra.getTotal()));
    }
        public void getproduct(){
        ProductoDAO proveDAO = new ProductoDAO();
        List<Producto> prove = proveDAO.listar();

        jtxProducto.removeAllItems();
        for(Producto pro:prove){
            jtxProducto.addItem(new Producto(pro.getIdProducto(), pro.getNombre()));
        }    
    }
    public void getsalida(){
        SalidaDAO proveDAO = new SalidaDAO();
        List<Salida> prove = proveDAO.listar();

        jtxentrada.removeAllItems();
        for(Salida ent:prove){
            jtxentrada.addItem(new Salida(ent.getIdSalidaProducto(), ent.getCodigo()));
        }    
    }
    
    public void getPorcentaje(){
        
        listIva.removeAllItems();
        listIva.addItem(new Iva("0%",1));
        listIva.addItem(new Iva("12%",2));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        labSubTotal = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labIdProducto = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        labPrecio = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        labIva = new javax.swing.JLabel();
        labentrada = new javax.swing.JLabel();
        listIva = new javax.swing.JComboBox<>();
        labTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jtxProducto = new javax.swing.JComboBox<>();
        jtxentrada = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        labSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        labSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        labSubTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitle.setForeground(new java.awt.Color(11, 58, 82));
        labTitle.setText("Modificar Detalle Salida");
        labSubTotal.add(labTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        labIdProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labIdProducto.setText("ID Producto");
        labSubTotal.add(labIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Cancelar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        labSubTotal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 90, 30));

        btnGuardar1.setBackground(new java.awt.Color(11, 58, 82));
        btnGuardar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("Guardar");
        btnGuardar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        labSubTotal.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 90, 30));

        labPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPrecio.setText("Sub Total");
        labSubTotal.add(labPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtSubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });
        labSubTotal.add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 200, 30));

        labIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labIva.setText("Porcentaje IVA");
        labSubTotal.add(labIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        labentrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labentrada.setText("ID Salida");
        labSubTotal.add(labentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, -1));

        listIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listIvaActionPerformed(evt);
            }
        });
        labSubTotal.add(listIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 190, 30));

        labTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labTotal.setText("Total");
        labSubTotal.add(labTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        labSubTotal.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 200, 30));

        jtxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxProductoActionPerformed(evt);
            }
        });
        labSubTotal.add(jtxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 170, 30));

        jtxentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxentradaActionPerformed(evt);
            }
        });
        labSubTotal.add(jtxentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        
        DetalleSalida entra = new DetalleSalida();
        DetalleSalidaDAO entraDAO = new DetalleSalidaDAO();
        
        if(
                !txtSubTotal.getText().equals("") && 
                !txtTotal.getText().equals("") ){          
               entra.setIdSalidaProducto(String.valueOf(jtxentrada.getItemAt(jtxentrada.getSelectedIndex()).getIdSalidaProducto()));
            entra.setIdProducto(String.valueOf(jtxProducto.getItemAt(jtxProducto.getSelectedIndex()).getIdProducto()));     
           
            entra.setSubtotal(Float.parseFloat(txtSubTotal.getText()));
            entra.setValorIva((int) listIva.getItemAt(listIva.getSelectedIndex()).getValor());                                           
                entra.setEstado(1);
                entra.setFechaModifica(LocalDateTime.now());
                entra.setUsuarioModifica(sysUser.getUsername());
                            
                
                    if(entraDAO.modificar(entra)){                           
                        this.dispose();
                        formDetalleSalida.getEntradas();

                    }else{
                        JOptionPane.showMessageDialog(null, "No se guardaron los datos.");
                    }
              
                        
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos del formulario.");
        }
        
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jtxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxProductoActionPerformed

    private void listIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listIvaActionPerformed

    private void jtxentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxentradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDetalleSalidaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDetalleSalidaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDetalleSalidaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDetalleSalidaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDetalleSalidaEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<Producto> jtxProducto;
    private javax.swing.JComboBox<Salida> jtxentrada;
    private javax.swing.JLabel labIdProducto;
    private javax.swing.JLabel labIva;
    private javax.swing.JLabel labPrecio;
    private javax.swing.JPanel labSubTotal;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labTotal;
    private javax.swing.JLabel labentrada;
    private javax.swing.JComboBox<Iva> listIva;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
